pipeline {
    agent any

    tools {
        nodejs 'node'
    }

    environment {
        APP_NAME = "api-search-front"
        VERSION = "1.0.${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm  
                script {
                    env.LAST_COMMIT = sh(script: "git log -1 --pretty=%B", returnStdout: true).trim()
                    env.BRANCH = sh(script: "git name-rev --name-only HEAD | sed 's|remotes/origin/||'", returnStdout: true).trim()
                    echo "Branch: ${env.BRANCH}"
                }
            }
        }

        stage('Build') {
            steps {
                sh '''
                echo "Installing dependencies"
                npm ci

                echo "Dependencies OK"
                echo "Running Angular build"
                npx ng build --configuration production
                echo "Angular build OK"
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                export CHROME_BIN=/usr/bin/google-chrome
                npm run test -- --watch=false --browsers=ChromeHeadless
                echo "--- arquivos gerados ---"
                ls -la test-results/ || echo "pasta test-results nao existe"
                '''
            }
        }

        stage('Package') {
            steps {
                sh '''
                echo "Packaging Angular dist"
                mkdir -p package
                
                # 1. Gera o .tar.gz
                tar -czf package/$APP_NAME-$VERSION.tar.gz \
                -C dist/project_FrontEnd/browser .

                # 2. Gera o .zip (Rodando em subshell para não alterar o diretório base do resto do script)
                (cd dist/project_FrontEnd && zip -r ../../package/$APP_NAME-$VERSION.zip .)

                echo "Packages created successfully "
                '''
            }
        }

        stage('Deploy Staging') {
            when {
                expression { env.BRANCH == 'staging' }
            }
            steps {
                withCredentials([
                    string(credentialsId: 'TOKEN_VERCEL_JENKINS', variable: 'TOKEN'),
                    string(credentialsId: 'VERCEL_ORG_ID', variable: 'ORG_ID'),
                    string(credentialsId: 'VERCEL_ORG_ID_APISEARCH_STAGING', variable: 'PROJECT_ID')
                ]) {
                    sh '''
                    echo "Deploying to STAGING"
                    rm -rf .vercel
                    rm -rf dist-staging && mkdir -p dist-staging
                    tar -xzf package/$APP_NAME-$VERSION.tar.gz -C dist-staging
                    cp vercel.json dist-staging/vercel.json 

                    VERCEL_ORG_ID=$ORG_ID \
                    VERCEL_PROJECT_ID=$PROJECT_ID \
                    npx vercel dist-staging \
                        --token $TOKEN \
                        --yes \
                        --prod

                    echo "Staging deploy OK "
                    '''
                }
            }
        }

        stage('Deploy Production') {
            when {
                expression { env.BRANCH == 'main' }
            }
            steps {
                withCredentials([
                    string(credentialsId: 'TOKEN_VERCEL_JENKINS', variable: 'TOKEN'),
                    string(credentialsId: 'VERCEL_ORG_ID', variable: 'ORG_ID'),
                    string(credentialsId: 'VERCEL_ORG_ID_APISEARCH_PRODUCTION', variable: 'PROJECT_ID')
                ]) {
                    sh '''
                    echo "Deploying to PRODUCTION"
                    rm -rf .vercel
                    rm -rf dist-prod && mkdir -p dist-prod
                    tar -xzf package/$APP_NAME-$VERSION.tar.gz -C dist-prod
                    cp vercel.json dist-prod/vercel.json 

                    VERCEL_ORG_ID=$ORG_ID \
                    VERCEL_PROJECT_ID=$PROJECT_ID \
                    npx vercel dist-prod \
                        --token $TOKEN \
                        --yes \
                        --prod

                    echo "Production deploy OK "
                    '''
                }
            }
        }

        stage('Audit') {
            steps {
                sh '''
                mkdir -p audit

                echo "Pipeline OK" > audit/audit-log.txt
                echo "App: $APP_NAME" >> audit/audit-log.txt
                echo "Version: $VERSION" >> audit/audit-log.txt
                echo "Build already executed in Build stage" >> audit/audit-log.txt
                '''
            }
        }
    }

    post {
        success {
            emailext(
                subject: "🚀 Done Pipeline - ${JOB_NAME} #${BUILD_NUMBER}",
                body: """

                🚀 Done Pipeline!

                📝 Last Commit:
                ${env.LAST_COMMIT}


                🧪 Build: SUCCESS
                🚀 Deploy: SUCCESS
                🚨 Notify: SENT

                📦 Project: ${JOB_NAME}
                🌿 Branch: [${env.GIT_BRANCH}]
                👤 ILSolutions

                🔢 Build Number: ${BUILD_NUMBER}
                🖥️ Jenkins: ${JENKINS_URL}

                🔗 Build URL:
                ${BUILD_URL}

                """,
                to: "igor.luan.solutions@gmail.com"
            )
        }

        failure {
            emailext(
                subject: "❌ Failed Pipeline ! - ${JOB_NAME} #${BUILD_NUMBER}",
                body: """

                ❌ Failed Pipeline !

                📝 Last Commit:
                ${env.LAST_COMMIT}

                📦 Project: ${JOB_NAME}
                🌿 Branch: [${env.GIT_BRANCH}]

                🔢 Build Number: ${BUILD_NUMBER}

                🔗 Check:
                ${BUILD_URL}
                """,
                to: "igor.luan.solutions@gmail.com"
            )
        }

        always {
            junit '**/test-results/results.xml' 
            archiveArtifacts 'package/*.*'
        }
    }
}