pipeline {
    agent any

    tools {
        nodejs 'node'
    }

    environment {
        APP_NAME = "api-search-front"
        VERSION = "1.0.${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checkout OK'

                git branch: 'main',
                url: 'https://github.com/C14-INATEL/API_Search_FRONTEND.git'
            }
        }

        stage('Build') {
            steps {
                sh '''
                echo "Installing dependencies"

                npm ci

                echo "Dependencies OK"

                echo "Running Angular build"

                npx ng build --configuration production

                echo "Angular build OK"
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                echo "Test OK"
                '''
            }
        }

        stage('Package') {
            steps {
                sh '''
                echo "Packaging Angular dist"
                mkdir -p package
                tar -czf package/$APP_NAME-$VERSION.tar.gz \
                -C dist/project_FrontEnd .

                echo "Package created successfully"
                '''
            }
        }

        stage('Deploy Staging') {
            when {
                branch 'staging'
            }

            steps {
                sh '''
                echo "Deploy Staging OK"
                '''
            }
        }

        stage('Deploy Production') {
            when {
                branch 'main'
            }

            steps {
                sh '''
                echo "Deploy Production OK"
                '''
            }
        }

        stage('Audit') {
            steps {
                sh '''
                mkdir -p audit

                echo "Pipeline OK" > audit/audit-log.txt
                echo "App: $APP_NAME" >> audit/audit-log.txt
                echo "Version: $VERSION" >> audit/audit-log.txt
                echo "Build: $BUILD_NUMBER" >> audit/audit-log.txt
                '''
            }
        }
    }

    post {

        success {
            echo 'PIPELINE SUCCESS'
        }

        failure {
            echo 'PIPELINE FAILURE'
        }

        always {

            archiveArtifacts artifacts: 'package/*', fingerprint: true

            archiveArtifacts artifacts: 'audit/*', fingerprint: true

            echo 'Artifacts archived'
        }
    }
}