pipeline {
    agent any

    tools {
        nodejs 'node'
    }

    environment {
        APP_NAME = "api-search-front"
        VERSION = "1.0.${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout'){
            steps {
                git branch: 'main', url: 'https://github.com/C14-INATEL/API_Search_FRONTEND.git'
            }
        }

        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npx ng build --configuration production'
            }
        }

        stage('Package Version'){
            steps {
                sh '''
                echo "Packaging Angular dist"
                cd dist
                tar -czf $APP_NAME-$VERSION.tar.gz *
                mkdir -p ../package
                mv $APP_NAME-$VERSION.tar.gz ../package/
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                export CHROME_BIN=/usr/bin/chromium-browser
                export CHROME_FLAGS="--no-sandbox --disable-dev-shm-usage --disable-gpu"

                npm ci
                npx ng test --watch=false --code-coverage --browsers=ChromeHeadless
                '''
            }
        }

        stage('Deploy Staging') {
            when { expression { env.GIT_BRANCH == 'origin/staging' } }
            steps {
                sh '''
                echo "Deploy in staging"
                mkdir -p staging
                cp package/$APP_NAME-$VERSION.tar.gz staging/
                '''
            }
        }

        stage('Deploy Production') {
            when { expression { env.GIT_BRANCH == 'origin/main' } }
            steps {
                sh '''
                echo "Deploy in production"
                mkdir -p prod
                cp package/$APP_NAME-$VERSION.tar.gz prod/
                '''
            }
        }

        stage('Init Audit Folder') {
            steps {
                sh 'mkdir -p audit logs'
            }  
        }

        stage('Build Production Log') {
            steps {
                sh '''
                echo "1️⃣ BUILD PRODUCTION" > audit/audit-log.txt
                echo "--------------------------------" >> audit/audit-log.txt
                npx ng build --configuration=production >> audit/audit-log.txt 2>&1
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                echo "" >> audit/audit-log.txt
                echo "2️⃣ TESTES AUTOMATIZADOS" >> audit/audit-log.txt
                echo "--------------------------------" >> audit/audit-log.txt
                npx ng test --watch=false --browsers=ChromeHeadless >> audit/audit-log.txt 2>&1
                '''
            }
        }

        stage('Git Changes Log') {
            steps {
                sh '''
                echo "" >> audit/audit-log.txt
                echo "3️⃣ ALTERAÇÕES NO CÓDIGO" >> audit/audit-log.txt
                echo "--------------------------------" >> audit/audit-log.txt
                echo "Último commit:" >> audit/audit-log.txt
                git log -1 >> audit/audit-log.txt
                echo "" >> audit/audit-log.txt
                echo "Arquivos alterados:" >> audit/audit-log.txt
                git diff --name-status HEAD~1 >> audit/audit-log.txt
                '''
            }
        }

        stage('Artifacts Log') {
            steps {
                sh '''
                echo "" >> audit/audit-log.txt
                echo "4️⃣ ARTEFATOS GERADOS" >> audit/audit-log.txt
                echo "--------------------------------" >> audit/audit-log.txt
                ls -R dist >> audit/audit-log.txt
                du -sh dist >> audit/audit-log.txt
                '''
            }
        }

        stage('Pipeline Metadata') {
            steps {
                sh '''
                echo "" >> audit/audit-log.txt
                echo "5️⃣ METADADOS DA PIPELINE" >> audit/audit-log.txt
                echo "--------------------------------" >> audit/audit-log.txt
                echo "App: $APP_NAME" >> audit/audit-log.txt
                echo "Version: $VERSION" >> audit/audit-log.txt
                echo "Branch: $GIT_BRANCH" >> audit/audit-log.txt
                echo "Build Number: $BUILD_NUMBER" >> audit/audit-log.txt
                echo "Build URL: $BUILD_URL" >> audit/audit-log.txt
                echo "Date: $(date)" >> audit/audit-log.txt
                '''
            }
        }

        stage('Send Audit Log To API') {
            steps {
                sh '''
                LOG=$(cat audit/audit-log.txt | sed 's/"/\\"/g')
                curl -X POST $DEPLOY_API_URL \
                -H "Content-Type: application/json" \
                -d "{\\"log\\":\\"$LOG\\", \\"version\\":\\"$VERSION\\"}"
                '''
            }
        }

    }

    post {
        success {
            emailext(
                subject: "🚀 Done Front Pipeline - ${JOB_NAME} #${BUILD_NUMBER}",
                body: """
                🚀 Done Front Pipeline!
                🧪 Build: SUCCESS
                🚀 Deploy: SUCCESS
                🔬 Test: SUCCESS
                📃 Logs: STORED
                📦 Project: ${JOB_NAME}
                🌿 Branch: ${GIT_BRANCH}
                🔢 Build Number: ${BUILD_NUMBER}
                🔗 ${BUILD_URL}
                """,
                to: "igor.luan.solutions@gmail.com"
            )
        }

        failure {
            emailext(
                subject: "❌ Failed Front Pipeline! - ${JOB_NAME} #${BUILD_NUMBER}",
                body: """
                ❌ Failed Pipeline!
                📦 Project: ${JOB_NAME}
                🌿 Branch: ${GIT_BRANCH}
                🔢 Build Number: ${BUILD_NUMBER}
                🔗 ${BUILD_URL}
                """,
                to: "igor.luan.solutions@gmail.com"
            )
        }

        always {
            archiveArtifacts 'package/*.tar.gz'
            archiveArtifacts 'audit/audit-log.txt'
        }
    }
}